services:
  db:
    image: postgres:16-alpine
    container_name: church_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: church_scheduler
      POSTGRES_USER: church_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - "5433:5432"
    volumes:
      - pgdata_church:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U church_admin -d church_scheduler"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: church_app
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://church_admin:${POSTGRES_PASSWORD}@db:5432/church_scheduler
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "127.0.0.1:8501:8501"
    command: >
      streamlit run app.py
      --server.address=0.0.0.0
      --server.port=8501
      --server.headless=true

volumes:
  pgdata_church: